// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class Achievements
{
        public const string achievement_kaboom = "CgkIrNyjyeIVEAIQBQ"; // <GPGSID>
        public const string achievement_threat_him_right = "CgkIrNyjyeIVEAIQBA"; // <GPGSID>
        public const string leaderboard_slamster_leaderboard_wall_hits = "CgkIrNyjyeIVEAIQBw"; // <GPGSID>
        public const string achievement_ready_for_launch = "CgkIrNyjyeIVEAIQBg"; // <GPGSID>
        public const string leaderboard_slamster_leaderboard_time_attack = "CgkIrNyjyeIVEAIQAg"; // <GPGSID>
        public const string achievement_this_was_a_quicky = "CgkIrNyjyeIVEAIQAQ"; // <GPGSID>
        public const string achievement_speedy_hamster = "CgkIrNyjyeIVEAIQAw"; // <GPGSID>
        public const string achievement_oh_my_god_hackz = "CgkIrNyjyeIVEAIQCA"; // <GPGSID>
}

